[package]
name = "GarbageDetector"
version = "0.0.1"
authors = ["Bianca"]
license = "MIT"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "mainnet" }

[addresses]
garbage = "0x0"
